# Generated by Django 5.1.5 on 2025-02-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_shift_user_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(choices=[('AM', 'Am'), ('PM', 'Pm')], default='AM', max_length=2),
        ),
    ]
