# Generated by Django 5.1.5 on 2025-02-05 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_shift_shift_end_alter_shift_shift_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='shift',
            new_name='shift_available',
        ),
    ]
