# Generated by Django 5.1.5 on 2025-02-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_shift_user_shift_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Employee', 'Employee')], default='Employee', max_length=10),
        ),
    ]
