# Generated by Django 5.1.5 on 2025-02-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='main_protein',
            field=models.CharField(blank=True, choices=[('Chicken', 'Chicken'), ('Beef', 'Beef'), ('Prawns', 'Prawns'), ('Vegetables', 'Vegetables'), ('Fish', 'Fish')], max_length=20, null=True),
        ),
    ]
