# Generated by Django 5.1.5 on 2025-02-14 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_dishtype_alter_category_dish_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='dish_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.dishtype'),
        ),
    ]
