# Generated by Django 5.1.5 on 2025-02-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_category_dish_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='extra_dish_type',
        ),
        migrations.AddField(
            model_name='dishtype',
            name='extra_dish_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
