# Generated by Django 5.1.5 on 2025-02-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_category_extra_dish_type_and_more'),
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shift',
        ),
        migrations.AlterField(
            model_name='user',
            name='shift_available',
            field=models.ManyToManyField(blank=True, to='shifts.shift'),
        ),
    ]
