# Generated by Django 5.1.1 on 2025-04-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_delete_shift_alter_user_shift_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Employee', 'Employee'), ('Kitchen Staff', 'Kitchen Staff')], default='Employee', max_length=20),
        ),
    ]
