# Generated by Django 5.1.6 on 2025-05-01 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_user_role'),
        ('inventory', '0004_alter_inventory_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
        ),
    ]
