# Generated by Django 5.1.5 on 2025-03-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_tips', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_serviceCharge', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
