# Generated by Django 5.1.5 on 2025-03-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financereport',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financereport',
            name='total_serviceCharge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financereport',
            name='total_tips',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
