# Generated by Django 5.1.1 on 2025-04-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
