# Generated by Django 5.1.6 on 2025-05-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventory_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
