# Generated by Django 5.1.5 on 2025-03-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posFin', '0005_orderitem_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='num_people',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('dine-in', 'dine-in'), ('takeaway', 'takeaway')], default='dine-in', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
