# Generated by Django 5.1.5 on 2025-03-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posFin', '0006_order_num_people_order_order_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tips',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
