# Generated by Django 5.1.5 on 2025-03-27 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posFin', '0007_order_tips'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableNo', models.IntegerField(unique=True)),
                ('max_seating', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='table_Number',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='posFin.table'),
            preserve_default=False,
        ),
    ]
