# Generated by Django 5.1.5 on 2025-03-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posFin', '0009_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
