# Generated by Django 5.1.1 on 2025-04-21 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posFin', '0012_alter_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='table_Number',
        ),
    ]
