# Generated by Django 5.1.1 on 2025-04-21 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posFin', '0013_remove_order_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_Number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posFin.table'),
        ),
    ]
