# Generated by Django 5.1.5 on 2025-02-25 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_rota'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='max_employee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
