# Generated by Django 5.1.5 on 2025-05-03 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0006_alter_shiftavailability_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rota',
            name='shifts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.shiftavailability'),
        ),
    ]
