# Generated by Django 5.1.5 on 2025-05-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0007_alter_rota_shifts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rota',
            name='users',
        ),
        migrations.AddField(
            model_name='rota',
            name='days',
            field=models.DateField(blank=True, null=True),
        ),
    ]
