# Generated by Django 5.1.5 on 2025-05-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0008_remove_rota_users_rota_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rota',
            name='shifts',
        ),
        migrations.AddField(
            model_name='rota',
            name='shifts',
            field=models.ManyToManyField(to='shifts.shiftavailability'),
        ),
    ]
