# Generated by Django 5.1.5 on 2025-05-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0010_week_remove_rota_days_rota_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rota',
            name='week',
        ),
        migrations.AddField(
            model_name='rota',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rota',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Week',
        ),
    ]
