# Generated by Django 5.1.5 on 2025-05-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0011_remove_rota_week_rota_end_date_rota_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rota',
            name='end_date',
            field=models.DateField(blank=True, null=True, unique_for_date=True),
        ),
        migrations.AlterField(
            model_name='rota',
            name='start_date',
            field=models.DateField(blank=True, null=True, unique_for_date=True),
        ),
    ]
