# Generated by Django 5.1.5 on 2025-05-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0012_alter_rota_end_date_alter_rota_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rota',
            name='end_date',
            field=models.DateField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='rota',
            name='start_date',
            field=models.DateField(blank=True, null=True, unique=True),
        ),
    ]
